"""init schema: competitions, problems, climbers, attempts

Revision ID: 3da3caf1b6f8
Revises: 963efc647957
Create Date: 2025-10-07 14:16:42.845412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da3caf1b6f8'
down_revision: Union[str, None] = '963efc647957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
