"""init schema: competitions, problems, climbers, attempts

Revision ID: 963efc647957
Revises: 
Create Date: 2025-10-07 14:12:55.041148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '963efc647957'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climbers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.String(length=20), nullable=False),
    sa.Column('selected_grade', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climbers_name'), 'climbers', ['name'], unique=True)
    op.create_index(op.f('ix_climbers_roles'), 'climbers', ['roles'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compname', sa.String(length=120), nullable=False),
    sa.Column('compdate', sa.Date(), nullable=False),
    sa.Column('comppart', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climber_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('bonus_attempt', sa.Integer(), nullable=False),
    sa.Column('top_attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['climber_id'], ['climbers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climber_id', 'problem_id', name='uq_climber_problem')
    )
    op.create_index(op.f('ix_problem_attempts_climber_id'), 'problem_attempts', ['climber_id'], unique=False)
    op.create_index(op.f('ix_problem_attempts_problem_id'), 'problem_attempts', ['problem_id'], unique=False)
    op.drop_table('problem_attempt')
    op.drop_table('climber')
    op.drop_table('competition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('compname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('compdate', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('comppart', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('climber',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('selected_grade', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('roles', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('problem_attempt',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bonus_attempt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_attempt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('climber_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['climber_id'], ['climber.id'], name='problem_attempt_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_problem_attempts_problem_id'), table_name='problem_attempts')
    op.drop_index(op.f('ix_problem_attempts_climber_id'), table_name='problem_attempts')
    op.drop_table('problem_attempts')
    op.drop_table('problems')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_climbers_roles'), table_name='climbers')
    op.drop_index(op.f('ix_climbers_name'), table_name='climbers')
    op.drop_table('climbers')
    # ### end Alembic commands ###
